Sign in
wolox-training/ge-express-js pull request #6
Opened 2019-06-10 19:00 UTC by gon-escalante

## Summary

added sign in with token authentication

## Trello Card

https://trello.com/c/sddnkqKi/3-sign-in

2019-06-12 17:56 UTC, picollomartin requested changes

2019-06-12 17:56 UTC, picollomartin commented on package.json
>      "jwt-simple": "^0.5.1",
`jwt-simple` and `jsonwebtoken` does the same, use only one

2019-06-12 17:56 UTC, picollomartin commented on app/services/user.js
> +  User.findOne({ where: { email } }).catch(err => next(databaseError(err)));
Services should not receive `next` callback, passing error to middlewares or not is responsibility of controller, throw error from here and catch later

2019-06-12 17:56 UTC, picollomartin commented on app/routes.js
> +  app.post('/users/session', [], userController.signIn);
Remove empty middlewares array

2019-06-12 17:56 UTC, picollomartin commented on app/controllers/user.js
> +  } = require('../../config'),
This does the same and looks better for this, `{  secret  } = require('../../config').common.session`

2019-06-12 17:56 UTC, picollomartin commented on app/controllers/user.js
> +        return res.status(400).send(['Email not found']);
Use a next for passing errors

2019-06-12 17:56 UTC, picollomartin commented on app/controllers/user.js
> +        return res.status(401).send('Unauthorized');
Same here

2019-06-12 17:56 UTC, picollomartin commented on app/controllers/user.js
> +          const token = jwt.sign({ userId: user.id }, secret);
Maybe is useful have token actions as a service

2019-06-12 17:56 UTC, mpicollo-wolox commented on app/controllers/user.js
> +          return res.status(200).send(token);
`res.send(something)` already send status code 200

2019-06-12 17:56 UTC, mpicollo-wolox commented on app/controllers/user.js
> +      return defaultError(err);
This should be sent to `next`

2019-06-12 17:56 UTC, mpicollo-wolox commented on app/controllers/album.js
> +      return apiError(err.message);
Sent this to `next` middleware

2019-06-12 17:56 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    .then(encryptedPassword => createUser({ ...req.body, password: encryptedPassword }, next))
Spread body could be potentially dangerous if client sends some extra fields

2019-06-13 20:56 UTC, gon-escalante commented on app/controllers/user.js
> +  } = require('../../config'),
![image](https://user-images.githubusercontent.com/34032882/59466819-9a39bf80-8e04-11e9-9f26-4fe9f7be50fc.png)

2019-06-13 21:08 UTC, gon-escalante commented on app/controllers/user.js
> +        return res.status(401).send('Unauthorized');
ill fix this in the next pr because i already added an unauthorized error there 🌵

2019-06-14 17:18 UTC, picollomartin approved these changes

2019-06-14 17:18 UTC, mpicollo-wolox commented on app/controllers/user.js
> +    .catch(err => next(databaseError(err)))
Specific errors like `databaseErrors` or `apiErrors` should be throw by services, in that way anywhere when is used error is already formatted

```
...some code
service1.action().catch(err => next(error1(err)))
.then(() => service2.action2().catch(err => next(error2(err))))
.then(...logic)
```
vs
```
...some code
service1.action()
.then(() => service2.action2()))
.then(...logic)
.catch(next)
```

2019-06-18 15:22 UTC, merged