added heroku sequelize connection
wolox-training/ge-express-js pull request #9
Opened 2019-06-13 13:34 UTC by gon-escalante

## Summary

now properly connecting to heroku postgres database

## Trello Card

https://trello.com/c/Re3ucb8G/16-hacer-deploy-con-heroku

2019-06-18 16:43 UTC, picollomartin approved these changes

2019-06-18 18:55 UTC, igna92ts requested changes

2019-06-18 18:55 UTC, igna92ts commented on app/models/index.js
> +const sequelize = process.env.DATABASE_URL
why is DATABASE_URL coming directly from process.env rather than a property in the config?

2019-06-21 14:48 UTC, igna92ts approved these changes

2019-06-21 19:42 UTC, merged